# Generated by Django 4.1.7 on 2023-07-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycles',
            fields=[
                ('Cycle_id', models.AutoField(primary_key=True, serialize=False)),
                ('Cycle_name', models.CharField(max_length=50)),
                ('Category', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('image', models.ImageField(default='', upload_to='store')),
            ],
        ),
    ]
