# Generated by Django 4.1.7 on 2023-07-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycles',
            name='manufacturer',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cycles',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cycles',
            name='Cycle_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
